if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export TERM=xterm-256color

# put zsh into vi-mode and reduce mode switch delay
bindkey -v
KEYTIMEOUT=1

# set history
export HISTFILE=~/.zhistory
export HISTSIZE=1000000
export SAVEHIST=1000000
setopt append_history
setopt extended_history
setopt inc_append_history
setopt interactivecomments

# Auto CD
setopt auto_cd

autoload -Uz compinit
typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
  compinit -i
else
  compinit -C -i
fi

# Load antibody plugins
source ~/.zsh-plugins.sh

#load generic funcs/exports if they exist - wont be checked in
[[ -f $HOME/s/work-scripts.sh ]] && source $HOME/s/work-scripts.sh
[[ -f $HOME/s/extras.sh ]] && source $HOME/s/extras.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'

clear_scrollback() {
  printf '\033[2J\033[3J\033[1;1H'
}

# path
export PATH=$PATH:$(go env GOPATH)/bin
export GOPATH=$(go env GOPATH)

# aliases
# trailing space because https://unix.stackexchange.com/questions/25327/watch-command-alias-expansion
alias watch='watch '
alias vim=nvim
alias ls="exa -l --git"
alias l="exa -la --git"
alias k="kubectl"
alias kctx="kubectx"

# git aliases etc
source "$(eval echo ~$USER)/dotfiles/zsh/git.zsh"

# lazy load kubectl autocompletion
function kubectl() {
  if ! type __start_kubectl >/dev/null 2>&1; then
    source <(command kubectl completion zsh)
  fi

  command kubectl "$@"
}

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/dotfiles/zsh/p10k.zsh ]] || source ~/dotfiles/zsh/p10k.zsh
