precmd() { print "" }

# set history
export HISTFILE=~/.zhistory
export HISTSIZE=10000
export SAVEHIST=10000
setopt append_history
setopt extended_history
setopt inc_append_history

# Auto CD
setopt auto_cd

autoload -Uz compinit
typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
  compinit -i
else
  compinit -C -i
fi

# ~/.zshrc
source ~/.zsh_plugins.sh
#load generic funcs/exports if they exist
[[ -f $HOME/s/extras.sh ]] && source $HOME/s/extras.sh

# ruby env
eval "$(rbenv init -)"

alias l="exa -l --git"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
